apiVersion: v1
kind: Pod
metadata:
  labels:
    run: {{ .Values.database_name }}
  name: {{ .Values.database_name  }}
spec:
  containers:
  - env:
    - name: MYSQL_ROOT_PASSWORD
      value: {{ .Values.root_password }}
    - name: MYSQL_DATABASE
      value: {{ .Values.mysql_db }}
    - name: MYSQL_USER
      value: {{ .Values.user }}
    - name: MYSQL_PASSWORD
      value: {{ .Values.password }}
    image: {{ .Values.mysql_image }}
    name: {{ .Values.database_name }}
  restartPolicy: Always