apiVersion: v1
kind: Service
metadata:
  labels:
    run: {{ .Values.service_name }}
  name: {{ .Values.service_name }}
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: {{ .Values.wordpress_name }}
  type: NodePort
